language: java
jdk:
  - oraclejdk8
dist: trusty
sudo: required
addons:
      chrome: stable

cache:
  directories:
    - $HOME/.m2

before_cache:
  - rm -f $HOME/.m2/repository/io/cucumber

before_install:
 - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  ⋮
 - sudo chmod +x /chromedriver_win32/

install:
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn clean install
  - mvn test -B
