language: java
dist: trusty
jdk:
  - oraclejdk8

addons:
      chrome: stable

cache:
  directories:
    - $HOME/.m2

before_cache:
  - rm -f $HOME/.m2/repository/io/cucumber

before_install:
  # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  ⋮

install:
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn clean install
  - mvn test -B