language: java
jdk:
  - oraclejdk8
dist: trusty
sudo: required
addons:
      chrome: stable

cache:
  directories:
    - $HOME/.m2

before_cache:
  - rm -f $HOME/.m2/repository/io/cucumber
  
install:
  - mvn -N io.takari:maven:wrapper
  - wget -N https://chromedriver.storage.googleapis.com/88.0.4324.96/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn clean install
  - mvn test -B
